Rebase to 3.9 and change hash and keyserver
eht16/python3-docker pull request #1
Opened 2021-07-06 19:25 UTC by CobaltGit

2021-07-08 21:01 UTC, eht16 requested changes
Thanks, only two minor things:  cleanup in a temporary build stage is not necessary and I wouldn't agree on claiming this a fork :).

2021-07-08 21:01 UTC, eht16 commented on Dockerfile
> +		rm -rf /var/lib/apt/lists/*
This is not necessary and has been left out intentionally because here we are in a temporary build stage which is thrown away after the image has been built. Only the contents in `/python` are copied over to the final build stage, everything else is dropped. So there is no need to cleanup.

2021-07-08 21:01 UTC, eht16 commented on README.md
> +## NOTE: THIS IS A FORK THAT AIMS TO KEEP UP TO DATE WITH THE LATEST PYTHON/PIP, THE ORIGINAL ISN'T BEING MAINTAINED ANYMORE.
How do you think so? :D

2021-07-09 17:02 UTC, CobaltGit commented on README.md
> +## NOTE: THIS IS A FORK THAT AIMS TO KEEP UP TO DATE WITH THE LATEST PYTHON/PIP, THE ORIGINAL ISN'T BEING MAINTAINED ANYMORE.
Thanks, I'll see if I can get to those asap.

2021-07-09 17:03 UTC, CobaltGit commented on README.md
> +## NOTE: THIS IS A FORK THAT AIMS TO KEEP UP TO DATE WITH THE LATEST PYTHON/PIP, THE ORIGINAL ISN'T BEING MAINTAINED ANYMORE.
Shit, I deleted the fork, I have a local copy though. I'll get to work when I'm free.

2021-07-10 18:42 UTC, CobaltGit commented
Made another PR, this time actually fulfilling your review.

2021-07-10 18:42 UTC, closed without merging