Rebase Pip to 21.2.1
eht16/python3-docker pull request #3
Opened 2021-07-29 13:47 UTC by CobaltGit

2021-08-01 21:40 UTC, eht16 commented on Dockerfile
> +ENV PYTHON_VERSION=3.9.6 \
This is not necessary (as well as the other changes in 9431c4a0efd10eced93b2ffaf11d1c0accfabb6d). As already explained in https://github.com/eht16/python3-docker/pull/1#discussion_r666512786: this is a temporary build container and all its layers will be dropped and will not be included in the final image.

2021-08-01 21:41 UTC, eht16 commented on Dockerfile
> +	apt-get purge --assume-yes --auto-remove -o APT::AutoRemove::RecommendsImportant=false && apt-get clean && \
Does `apt-get clean` anything meaningful more than `rm -rf /var/lib/apt/lists/*`?

2021-08-02 21:13 UTC, eht16 requested changes
Thanks for the followup.
Would you mind checking my comments?

2021-08-07 07:46 UTC, eht16 commented
@CobaltGit Would you mind checking my comments?

2021-08-08 11:35 UTC, CobaltGit commented
Sorry for the delay, I'll get to work now

2021-08-08 12:02 UTC, CobaltGit commented
Also, are you alright with the image being pushed to a public registry (Docker Hub preferred)?

2021-08-08 21:29 UTC, merged

2021-08-08 21:29 UTC, eht16 commented
> Also, are you alright with the image being pushed to a public registry (Docker Hub preferred)?

Yes, sure. As long as I don't have to do it :).

2021-08-09 11:06 UTC, cobaltgit commented
Oh don't worry, I'll take care of that

2021-08-09 11:16 UTC, cobaltgit commented
I'll also throw in variants with other base images e.g Ubuntu Focal

2021-08-09 14:13 UTC, cobaltgit commented
> I'll also throw in variants with other base images e.g Ubuntu Focal

https://hub.docker.com/repository/docker/cobaltdocker/eht16-python3/general

2021-08-09 21:15 UTC, eht16 commented
Nice!
You don't need to keep my name in the image name nor in the description. I don't mind at all :).